# Generated by Django 3.0.5 on 2020-06-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_details',
            table='User_Details',
        ),
    ]
