# Generated by Django 3.0.5 on 2020-06-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20200618_0026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_details',
            table=None,
        ),
    ]
